### ISSUE TITLE
Exemplary  code, small issues 

### ISSUE THREAD

**Issue by joy4u2** [tr1nh/customize-google-form#1]
Thank you for your fantastic efforts, it will help a lot of people during this COVID-19 times
Two things are missing in forms.pug hope you add it soon
1. Multi-Choice Grid
2. Tick box grid 

If one chooses to collect email id from setting, it does not work.

**Comment by tr1nh** [comment]
Thanks for your interest in my project. I added the missing features.

**Comment by joy4u2** [comment]
Awesome!!! Thanks a lot, it's working, haven't tried it on a live server, will keep you updated.
